version: '3.3'
services:
  mysql:
    # container_name: mysql
    hostname: mysql
    image: mysql:8
    environment:
      MYSQL_DATABASE: canopeum_db
      MYSQL_ROOT_PASSWORD: Canopeum12345!@
      MYSQL_USER: canopeum_user
      MYSQL_PASSWORD: CanopeumUser12345!@
    ports:
      - 6002:3306
    volumes:
      - mysql8-data:/var/lib/mysql
    networks:
      - bleh
    #   - nginx-canopeum
      # - internal-canopeum
      # local-canopeum:
      #   aliases:
      #     - mysql

  backend:
    # container_name: backend
    hostname: backend
    image: ghcr.io/beslogic/canopeum_backend:latest
    ports:
      - 6001:5001
    depends_on:
      - mysql
    environment:
      MYSQL_DATABASE: canopeum_db
      MYSQL_ROOT_PASSWORD: Canopeum12345!@
      MYSQL_HOST: mysql
      MYSQL_USER: canopeum_user
      MYSQL_PASSWORD: CanopeumUser12345!@
      VIRTUAL_HOST: api.canopeum.releaftrees.life
    networks:
      # - internal-canopeum
      - bleh
      # - local-canopeum

  frontend:
    # container_name: frontend
    hostname: frontend
    image: ghcr.io/beslogic/canopeum_frontend:latest
    ports:
      - 6000:80
    environment:
      VIRTUAL_HOST: releaftrees.life
    networks:
      # - nginx-canopeum
      # - local-canopeum

volumes:
  mysql8-data:

networks:
  bleh:
    external: true
  # internal-canopeum:
  #   external: true

  # local-canopeum:
  #   external: false
